import os
from building import *

objs = []
src = Glob('*.c')
cwd  = GetCurrentDir()
CPPPATH = [cwd]

objs = DefineGroup('Cybergear', src, depend = ['BSP_USING_CYBERGEAR_MOTOR'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
